############ MID Config #############
# optimizer
lr: 0.001
nei_attn_mask: True
nei_padding_mask: True
batch_size: 32

diffusion_steps: 300
# - 500
# - 2000
variance_mode: 'linear'
# 'linear', 'cosine'
val_mode: multistep
# Training Prarmeters:
diffnet: SpatialTransformer4 #TransformerConcatLinear

spatial_emsize: 128
spatial_encoder_head: 4
# spatial_encoder_hidden: 128
spatial_encoder_layers: 2
dropout: 0.3 #0.1 0.3
esti_goal: acce # acce, pos
history_dim: 6 # if esti_goal==acce 6 else 2d
history_emsize: 64
history_lstm: 256
history_lstm_out: 128
dest_emsize: 0
dest_hidden:
- 64
- 256

# context_dim = dest_emsize+history_lstm_out
obs_seq_len: 8
pred_seq_len: 20
epochs: 150

# dataset
data_path: configs/data_configs/data_finetune2_1.yaml
rebuild_dataset: False
data_dict_path: dataset_built/pretrain_gc_0115.pkl

dataset_type: timeindex
finetune_flag: 1
valid_steps: 20
data_dir: processed_data_sf
topk_ped: 6
sight_angle_ped: 90
dist_threshold_ped: 4
topk_obs: 10
sight_angle_obs: 90
dist_threshold_obs: 4
skip_frames: 25
num_history_feature: 8 
num_history_velocity: 1
train_mode: multi

  # the path with the directory with XXX.pkl

eval_batch_size: 256
k_eval: 25
seed: 123
eval_every: 15

# Testing
eval_at: 70
eval_mode: False

# Data Parameters:
device: cuda
eval_device: None
